      SUBROUTINE UHYPER(BI1,BI2,AJ,U,UI1,UI2,UI3,TEMP,NOEL,CMNAME,
     1                  INCMPFLAG,NUMSTATEV,STATEV,NUMFIELDV,
     2                 FIELDV,FIELDVINC,NUMPROPS,PROPS)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      DIMENSION UI1(3),UI2(6),UI3(6),STATEV(*),FIELDV(*),
     1        FIELDVINC(*),PROPS(*)
C
      PARAMETER (ZERO=0.0D0,ONE=1.0D0, TWO=2.0D0, THREE=3.0D0, 
     1    FOUR=4.0D0, FIVE=5.0D0)
C
C
C
C
C
     REMOVED FOR CONFIDENTIALITY
C
C
C
C
C
      RETURN
      END
